import { ApiService } from 'src/app/services/api.service';
import { environment } from './../../../../environments/environment.prod';
import { Input } from '@angular/core';
import { Restaurant } from '@qmenu/ui';
import { Component, OnInit } from '@angular/core';
import { GlobalService } from 'src/app/services/global.service';

@Component({
  selector: 'app-restaurant-bm-info',
  templateUrl: './restaurant-bm-info.component.html',
  styleUrls: ['./restaurant-bm-info.component.css']
})
export class RestaurantBmInfoComponent implements OnInit {

  @Input() restaurant: Restaurant;
  bmRT;
  constructor(private _api: ApiService, private _global: GlobalService) { }

  async ngOnInit() {
    this.loadRTInBM();
  }

  async loadRTInBM() {
    [this.bmRT] = await this._api.post(environment.biApiUrl + "smart-restaurant/api", {
      method: 'get',
      resource: 'bm-sst-restaurants',
      query: { GooglePlaceID: (this.restaurant.googleListing || {}).place_id },
      payload: {
        "_id": 1,
        "BusinessEntityID": 1,
        "BusinessName": 1,
        "GooglePlaceID": 1,
        "Phone1": 1,
        "Phone2": 1,
        "Phone3": 1,
        "Phone4": 1,
        "CellPhone1": 1,
        "CellPhone2": 1,
        "CellPhone3": 1,
        "CellPhone4": 1,
        "Address": 1,
        "AptUnitSuite": 1,
        "City": 1,
        "State": 1,
        "ZipCode": 1,
        "IsActive": 1,
        "IsPrepaid": 1,
        "LastClosedDateTime": 1,
        "LastGmbControlTime": 1,
        "IsBmGmbControl": 1,
        "CustomerDomainName": 1,
        "Last3rdMonthOC": 1,
        "Last2ndMonthOC": 1,
        "LastMonthOC": 1,
        "OrderFixedFeePerOrder": 1,
        "CreditCardFixedFeePerOrder": 1,
        "OrderMonthlyFee": 1,
        "CreditCardFeePercentage": 1,
        "AmexFeePercentage": 1,
        "OrderCommissionPercentage": 1,
        "FaxUnitPrice": 1,
        "PhoneUnitPrice": 1,
        "OrderCommissionMaximum": 1,
        "ReservationCommissionAmount": 1,
        "ReservationCommissionMaximum": 1,
        "MetropolitanAreaID": 1,
        "UsePhoneVerification": 1,
        "PhoneVerificationNumberTypeID": 1,
        "PartnerID": 1,
        "WebSiteStatisticsScript": 1,
        "FaxActive": 1,
        "CreditCardAllowVisa": 1,
        "CreditCardAllowMaster": 1,
        "CreditCardAllowAmericanExpress": 1,
        "CreditCardAllowDinnerCard": 1,
        "CreditCardAllowEnRoute": 1,
        "CreditCardAllowDiscover": 1,
        "CreditCardAllowJCB": 1,
        "Latitude": 1,
        "Longitude": 1,
        "Directions": 1,
        "PickupCookingTimeBuffer": 1,
        "DeliveryFoodPrepAndLeewayTimeMin": 1,
        "DeliveryFoodPrepAndLeewayTimeMax": 1,
        "DeliveryOrderMinimumAmount": 1,
        "MenuItemTaxRate": 1,
        "DeliveryTaxRate": 1,
        "ApplyDiscountsAfterTaxes": 1,
        "AllowPayByCash": 1,
        "AllowPayByCreditCard": 1,
        "TakeOutOrderEnable": 1,
        "DeliveryOrderEnable": 1,
        "CourierID": 1,
        "AfterOrderSendTextMessageToThisPhone": 1,
        "AfterOrderSendEmailToThisAddress": 1,
        "ReservationCateringActive": 1,
        "ReservationTableActive": 1,
        "ReservationSendTextMessageToThisPhone": 1,
        "ReservationSendEmailToThisAddress": 1,
        "ReservationUseFax": 1,
        "ReservationUseTelephoneNotification": 1,
        "Active": 1,
        "AboutusContent": 1,
        "CustomerDomainName1": 1,
        "DeliveryZone": 1,
        "StoreMessage": 1,
        "StoreMessageVisible": 1,
        "StoreMessageFromDateTime": 1,
        "StoreMessageToDateTime": 1,
        "IsROL": 1,
        "AllowOrderWhenNotOpen": 1,
        "PickupOrderMinimumAmount": 1,
        "DeliveryDescription": 1,
        "LocationPageUrl": 1,
        "PhotoGalleryPageUrl": 1,
        "ReceiptShowDeliveryDirection": 1,
        "ShowPaperMenuPage": 1,
        "ReceiptShowCustomerReceipt": 1,
        "DineInCookingTimeBuffer": 1,
        "DineInOrderMinimumAmount": 1,
        "DineInOrderEnable": 1,
        "ReceiptShowModifierBuilderTypeName": 1,
        "AptUnitSuite1": 1,
        "AllowUnknownAddressTakeOrder": 1,
        "DeliveryChargeText": 1,
        "HomePageUrl": 1,
        "ReservationEnable": 1,
        "ReservationNote": 1,
        "StoreEventEnable": 1,
        "FaxPlanID": 1,
        "AutoGeneratePopularItems": 1,
        "CreditCardRequirement": 1,
        "PhoneVerificationInputPinNumber": 1,
        "SurchargeText": 1,
        "SurchargeFixedFeePerOrder": 1,
        "SurchargePercentage": 1,
        "CreditCardProcessingFeeText": 1,
        "CreditCardProcessingFixedFeePerOrder": 1,
        "CreditCardProcessingPercentage": 1,
        "CreditCardAddressNumberRequired": 1,
        "ReceiptShowItemNumber": 1,
        "ReservationMinimumCustomerNumber": 1,
        "ReceiptPickupOrderShowCustomerAddress": 1,
        "PayCreditCardOnlineShowTipLine": 1,
        "AllowCustomerInputTip": 1,
        "MinimumTipForPayByCC": 1,
        "ThinClientReceiptFontSize": 1,
        "BusinessEntityGUID": 1,
        "CityNeighborhoodIDList": 1,
        "CityNeighborhoodNameList": 1,
        "ZipcodeList": 1,
        "CuisineIDList": 1,
        "CuisineNameList": 1,
        "HaveDiscount": 1,
        "HaveStoreClosingDay": 1,
        "BusinessEntityStatusTypeID": 1,
        "YelpBusinessID": 1,
        "RatingCount": 1,
        "RatingValue": 1,
        "ThinClientReceiptFontBold": 1,
        "SearchPriorityTypeID": 1,
        "PhonePlanID": 1,
        "AfterOrderSendEmailToPrinter": 1,
        "PrepaidDisableAmexCC": 1,
        "ReceiptHideTaxRate": 1,
        "EnableFutureOrders": 1,
        "DeliveryDinnerRushIncreaseBuffer": 1,
        "PickupDinnerRushIncreaseBuffer": 1,
        "CloudPrintFontRatio": 1,
        "DisableAutomaticConfirmations": 1,
        "AutoConfirmOrderAfterThinClient": 1,
        "ShowMenuGroupDefaultPhotos": 1,
        "EnableAutomaticEstimates": 1,
        "AllowCustomerInputTipNonPrepaid": 1,
        "DisableMenuItemInstructions": 1,
        "DisableOrderInstructions": 1,
        "NonPrepaidForceSmsVerification": 1,
      },
      limit: 1
    }).toPromise();
  }

}
