export const environment = {
  production: false,
  env: "dev",
  adminApiUrl: 'https://swozix2epl.execute-api.us-east-2.amazonaws.com/dev/',
  qmenuApiUrl: 'https://67dqylz39g.execute-api.us-east-2.amazonaws.com/dev/',
  legacyApiUrl: "https://quez.herokuapp.com/",
  autoGmbUrl: "http://localhost:3000/",
  socketUrl: "https://quez.herokuapp.com:443/",
  bizUrl: 'https://qa-biz.herokuapp.com/',
  customerUrl: 'https://qa-customer.herokuapp.com/',
  thumnailUrl: 'https://s3.amazonaws.com/chopstresized/128_menuImage/',
  normalResUrl: 'https://s3.amazonaws.com/chopstresized/768_menuImage/',
  stripePublishableKey: 'pk_test_PbXsKYfVeKPV4wlQP4wpQYfg',
  printServerEndPoint: "nvyzxm5z40.execute-api.us-east-1.amazonaws.com/dev",
  testOrderId: "5af213f552d5d11400e35550"
  // production: true,
  // env: "prod",
  // adminApiUrl: "https://swozix2epl.execute-api.us-east-2.amazonaws.com/prod/",
  // qmenuApiUrl: "https://67dqylz39g.execute-api.us-east-2.amazonaws.com/prod/",
  // legacyApiUrl: "https://api.myqmenu.com/",
  // autoGmbUrl: "http://localhost:3000/",
  // socketUrl: 'https://api.myqmenu.com/',
  // bizUrl: 'https://biz.qmenu.us/',
  // customerUrl: 'https://qmenu.us/',
  // thumnailUrl: 'https://s3.amazonaws.com/chopstresized/128_menuImage/',
  // normalResUrl: 'https://s3.amazonaws.com/chopstresized/768_menuImage/',
  // stripePublishableKey: 'pk_live_uSs2MVVyG0vn6TICsTIyXG6Y',
  // printServerEndPoint: "nvyzxm5z40.execute-api.us-east-1.amazonaws.com/prod",
  // testOrderId: "5c720fd092edbd4b28883ee1"
};
