export const environment = {
  // production: false,
  // env: "dev",
  // appApiUrl: "https://9v8upsmsai.execute-api.us-east-1.amazonaws.com/dev/",
  // qmenuApiUrl: "https://67dqylz39g.execute-api.us-east-2.amazonaws.com/dev/",
  // utilsApiUrl: "https://08znsr1azk.execute-api.us-east-1.amazonaws.com/dev/",
  // legacyApiUrl: "https://quez.herokuapp.com/",
  // // legacyApiUrl: "http://localhost:1337/",
  // autoGmbUrl: "http://localhost:3000/",

  // migrationUrl: "http://qauto.ngrok.io/",
  // taskUrl: "https://qtask.ngrok.io/",
  // qmenuNgrok: "https://qmenu.ngrok.io/",
  // gmbNgrok: "https://gmb.ngrok.io/",
  // socketUrl: "https://quez.herokuapp.com:443/",
  // bizUrl: 'https://qa-biz.herokuapp.com/',
  // customerUrl: 'https://qa-customer.herokuapp.com/',
  // thumnailUrl: 'https://s3.amazonaws.com/chopstresized/128_menuImage/',
  // normalResUrl: 'https://s3.amazonaws.com/chopstresized/768_menuImage/',
  // stripePublishableKey: 'pk_test_PbXsKYfVeKPV4wlQP4wpQYfg',
  // testOrderId: "5af213f552d5d11400e35550"

  production: true,
  env: "prod",
  appApiUrl: "https://9v8upsmsai.execute-api.us-east-1.amazonaws.com/prod/",
  qmenuApiUrl: "https://67dqylz39g.execute-api.us-east-2.amazonaws.com/prod/",
  utilsApiUrl: "https://08znsr1azk.execute-api.us-east-1.amazonaws.com/prod/",
  legacyApiUrl: "https://api.myqmenu.com/",
  autoGmbUrl: "http://localhost:3000/",
  migrationUrl: "https://qauto.ngrok.io/",
  taskUrl: "https://qtask.ngrok.io/",
  qmenuNgrok: "http://localhost:8000/",
  gmbNgrok: "http://localhost:3030/",
  socketUrl: 'https://api.myqmenu.com/',
  bizUrl: 'https://biz.qmenu.us/',
  customerUrl: 'https://qmenu.us/',
  thumnailUrl: 'https://s3.amazonaws.com/chopstresized/128_menuImage/',
  normalResUrl: 'https://s3.amazonaws.com/chopstresized/768_menuImage/',
  stripePublishableKey: 'pk_live_uSs2MVVyG0vn6TICsTIyXG6Y',
  testOrderId: "5c720fd092edbd4b28883ee1"
};
