export const environment = {
  production: true,
  env: "prod",
  appApiUrl: "https://9v8upsmsai.execute-api.us-east-1.amazonaws.com/prod/",
  qmenuApiUrl: "https://67dqylz39g.execute-api.us-east-2.amazonaws.com/prod/",
  utilsApiUrl: "https://08znsr1azk.execute-api.us-east-1.amazonaws.com/prod/",
  legacyApiUrl: "https://api.myqmenu.com/",
  autoGmbUrl: "http://localhost:3000/",
  migrationUrl: "https://qauto.ngrok.io/",
  taskUrl: "https://qtask.ngrok.io/",
  invoicingApiUrl: "http://localhost:8888/",
  gmbNgrok: "https://gmb.ngrok.io/",
  bizUrl: 'https://biz.qmenu.us/',
  customerUrl: 'https://qmenu.us/',
  thumnailUrl: 'https://s3.amazonaws.com/chopstresized/128_menuImage/',
  normalResUrl: 'https://s3.amazonaws.com/chopstresized/768_menuImage/',
  stripePublishableKey: 'pk_live_uSs2MVVyG0vn6TICsTIyXG6Y',
  fattmerchantWebToken: 'qMenu-Inc-71e10ca6d824',
  testOrderId: "5c720fd092edbd4b28883ee1",
  shortUrlBase: "https://qmenu.biz/",
  customerPWAUrl: "https://qmenu.us/#/"
};
