export const environment = {
  production: false,
  env: "dev",
  appApiUrl: "https://9v8upsmsai.execute-api.us-east-1.amazonaws.com/dev/",
  qmenuApiUrl: "https://67dqylz39g.execute-api.us-east-2.amazonaws.com/dev/",
  utilsApiUrl: "https://08znsr1azk.execute-api.us-east-1.amazonaws.com/dev/",
  legacyApiUrl: "https://quez.herokuapp.com/",
  // legacyApiUrl: "http://localhost:1337/",
  autoGmbUrl: "http://localhost:3000/",
  migrationUrl: "http://qauto.ngrok.io/",
  taskUrl: "https://qtask.ngrok.io/",
  invoicingApiUrl: "http://localhost:8888/",
  gmbNgrok: "https://gmb.ngrok.io/",
  socketUrl: "https://quez.herokuapp.com:443/",
  bizUrl: 'https://qa-biz.qmenu.us/',
  customerUrl: 'https://qa-customer.herokuapp.com/',
  thumnailUrl: 'https://s3.amazonaws.com/chopstresized/128_menuImage/',
  normalResUrl: 'https://s3.amazonaws.com/chopstresized/768_menuImage/',
  stripePublishableKey: 'pk_test_PbXsKYfVeKPV4wlQP4wpQYfg',
  fattmerchantWebToken: 'qMenu-8c21919909a7',
  testOrderId: "5af213f552d5d11400e35550",
  shortUrlBase: "https://2vevc851r7.execute-api.us-east-1.amazonaws.com/dev/"

  // production: true,
  // env: "prod",
  // appApiUrl: "https://9v8upsmsai.execute-api.us-east-1.amazonaws.com/prod/",
  // qmenuApiUrl: "https://67dqylz39g.execute-api.us-east-2.amazonaws.com/prod/",
  // utilsApiUrl: "https://08znsr1azk.execute-api.us-east-1.amazonaws.com/prod/",
  // legacyApiUrl: "https://api.myqmenu.com/",
  // autoGmbUrl: "http://localhost:3000/",
  // migrationUrl: "https://qauto.ngrok.io/",
  // taskUrl: "https://qtask.ngrok.io/",
  // invoicingApiUrl: "http://localhost:8888/",
  // gmbNgrok: "https://gmb.ngrok.io/",
  // bizUrl: 'https://biz.qmenu.us/',
  // customerUrl: 'https://qmenu.us/',
  // thumnailUrl: 'https://s3.amazonaws.com/chopstresized/128_menuImage/',
  // normalResUrl: 'https://s3.amazonaws.com/chopstresized/768_menuImage/',
  // stripePublishableKey: 'pk_live_uSs2MVVyG0vn6TICsTIyXG6Y',
  // fattmerchantWebToken: 'qMenu-Inc-71e10ca6d824',
  // testOrderId: "5c720fd092edbd4b28883ee1",
  // shortUrlBase: "https://qmenu.biz/"
};
